import React, {useEffect, useState} from 'react';
import {Sprout, Flower2, Settings2, ArrowRight, Volume2, Heart, Eye, Ear, BookOpen, Sun, Sparkles, Check, ChevronRight, Map, Leaf, Image, Bug} from 'lucide-react';
import {topics,families,modes,levels} from './content.js';
import {readSaved,recordSession} from './game.js';
import {speak,silence} from './audio.js';
import Modal from './Modal.jsx';
import Exercise from './Exercise.jsx';
import History from './History.jsx';

const icons={eye:Eye,ear:Ear,book:BookOpen,picture:Image,bug:Bug};
const storageKey='jardin-des-sons-progress-v1';
function saved(){try{return readSaved(localStorage.getItem(storageKey));}catch{return readSaved(null);}}
function preferences(){try{const p=JSON.parse(localStorage.getItem('jardin-preferences'));return {large:!!p?.large,spaced:!!p?.spaced,version:2,level:p?.version===2&&levels.some(l=>l.id===p.level)?p.level:'words'};}catch{return {large:false,spaced:false,version:2,level:'words'};}}

export default function App(){
  const [selected,setSelected]=useState('p');
  const [progress,setProgress]=useState(saved);
  const [prefs,setPrefs]=useState(preferences);
  const [modal,setModal]=useState(null);
  const [exercise,setExercise]=useState(null);
  const [view,setView]=useState('map');
  const [audioError,setAudioError]=useState(false);
  const [storageError,setStorageError]=useState(false);
  const topic=topics.find(t=>t.id===selected);
  const family=families.find(f=>f.id===topic.family);
  const say=text=>speak(text,()=>setAudioError(true));
  useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(progress));}catch{setStorageError(true);}},[progress]);
  useEffect(()=>{try{localStorage.setItem('jardin-preferences',JSON.stringify(prefs));}catch{setStorageError(true);}},[prefs]);
  useEffect(()=>()=>silence(),[]);
  useEffect(()=>{
    if(!document.modelContext?.registerTool)return;
    const lifecycle=new AbortController();
    try{Promise.resolve(document.modelContext.registerTool({name:'select_reading_branch',title:'Choisir une branche',description:'Affiche la découverte du groupe de lettres choisi, sans répondre aux exercices.',inputSchema:{type:'object',properties:{grapheme:{type:'string',enum:topics.map(t=>t.id)}},required:['grapheme'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input || !topics.some(t=>t.id===input.grapheme))throw new Error('Branche inconnue');setSelected(input.grapheme);setView('map');await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {selected:input.grapheme};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
    return ()=>lifecycle.abort();
  },[]);
  function complete(result){setProgress(p=>recordSession(p,result));}
  function close(){silence();setModal(null);}
  return <div className={`app ${prefs.large?'large-text':''} ${prefs.spaced?'spaced-text':''}`}>
    <a className="skip-link" href="#main">Aller aux jeux</a>
    <header className="header"><a href="#" className="brand" onClick={e=>{e.preventDefault();setView('map');}}><span className="brand-icon"><Sprout size={28}/></span><span>le jardin<span className="brand-bottom">des sons<span className="brand-dot">.</span></span></span></a>
      <nav aria-label="Navigation principale"><button className={view==='map'?'nav-link active':'nav-link'} onClick={()=>setView('map')}><Map size={18}/> Ma carte</button><button className={view==='garden'?'nav-link active':'nav-link'} onClick={()=>setView('garden')}><Flower2 size={18}/> Mon jardin {progress.flowers>0&&<span className="nav-count">{progress.flowers}</span>}</button></nav>
      <div className="header-right"><button className="icon-button settings-toggle" onClick={()=>setModal('settings')} aria-label="Réglages de lecture"><Settings2 size={21}/></button><span className="header-divider"/><span className="avatar">E</span><span className="profile-name">Elisabeth</span></div>
    </header>
    <main id="main">
      <section className="welcome"><div><div className="greeting"><Sun size={17}/> BONJOUR ELISABETH</div><h1>{view==='map'?<>Fais grandir ta lecture<span className="heading-dot">.</span></>:<>Ton jardin grandit<span className="heading-dot">.</span></>}</h1><p>{view==='map'?'Un son, un petit jeu, une nouvelle découverte.':'Chaque fleur raconte une petite victoire.'}</p></div><div className="flower-counter"><span className="counter-icon"><Flower2 size={27}/></span><div><strong>{progress.flowers} {progress.flowers===1?'fleur cueillie':'fleurs cueillies'}</strong><span>Ça commence par une petite graine !</span></div></div></section>
      {view==='map'?<>
        <section className="level-bar" aria-label="Niveau de lecture"><div><span className="eyebrow">PRÊTE POUR UN NOUVEAU DÉFI ?</span><strong>Choisis ton aventure</strong></div><div className="level-options">{levels.map(l=><button key={l.id} className={prefs.level===l.id?'level-choice selected':'level-choice'} aria-pressed={prefs.level===l.id} onClick={()=>setPrefs(p=>({...p,level:l.id}))}><strong>{l.name}</strong><span>{l.description}</span></button>)}</div></section><div className="workspace">
          <section className="map-panel" aria-labelledby="map-title"><div className="panel-heading"><div><span className="eyebrow">À TOI D’EXPLORER</span><h2 id="map-title">Ma carte des sons</h2></div><span className="map-label"><span/> 3 chemins à découvrir</span></div>
            <div className="mind-map">
              <svg className="connections" viewBox="0 0 760 440" preserveAspectRatio="none" aria-hidden="true"><path d="M360 236 C260 236 260 105 174 105" className="peach-line"/><path d="M401 213 C466 213 457 100 555 100" className="lilac-line"/><path d="M407 254 C475 254 451 348 565 348" className="blue-line"/><path d="M337 269 C280 290 276 358 204 358" className="green-line"/></svg>
              <div className="map-center"><span className="center-icon"><Sprout size={39} strokeWidth={1.8}/></span><strong>Mes petits<br/>sons</strong><span>Je découvre, je grandis</span></div>
              {families.map(f=><div className={`branch ${f.id} ${f.color}`} key={f.id}><div className="branch-heading"><span aria-hidden="true">{f.emoji}</span><h3>{f.title}</h3></div><p>{f.subtitle}</p><div className="letter-list">{f.letters.map(letter=><button key={letter} className={`letter-chip ${selected===letter?'selected':''}`} aria-label={`Découvrir ${letter}`} aria-pressed={selected===letter} onClick={()=>setSelected(letter)}>{letter}{progress.completed.includes(letter)&&<Check className="chip-check" size={12}/>}</button>)}</div></div>)}
              <div className="map-note"><span className="note-icon"><Heart size={19}/></span><p>Les petites étapes<br/>font les grands progrès.</p><span className="note-sparkle">✦</span></div>
              <span className="map-decoration deco-1" aria-hidden="true">✧</span><span className="map-decoration deco-2" aria-hidden="true">✦</span>
            </div>
            <div className="map-caption"><span className="step-circle">1</span> Choisis une lettre sur la carte <ChevronRight size={16}/><span className="step-circle">2</span> Découvre-la et joue !</div>
          </section>
          <aside className={`discovery ${family.color}`} aria-labelledby="discovery-title"><div className="discovery-top"><span className="eyebrow">TA DÉCOUVERTE DU MOMENT</span><Sparkles size={19}/></div><div className="discovery-example"><span className="hero-letter" aria-hidden="true">{topic.id}</span><span className="word-picture" aria-hidden="true">{topic.emoji}</span></div><h2 id="discovery-title"><strong>{topic.id}</strong> comme dans <strong>{topic.word}</strong></h2><button className="sound-button" onClick={()=>say(topic.word)}><Volume2 size={19}/> Écouter le mot</button><p className="letter-tip">{topic.tip}</p><div className="syllable-label">On essaie ensemble ?</div><div className="syllables">{topic.syllables.slice(0,3).map(s=><button key={s} onClick={()=>say(s)} aria-label={`Écouter ${s}`}>{s}<Volume2 size={13}/></button>)}</div><button className="primary discovery-cta" onClick={()=>setExercise(prefs.level==='syllables'?'observe':'picture')}>{prefs.level==='challenge'?'Le défi des mots':`Jouer avec ${topic.id}`}<ArrowRight size={20}/></button><span className="micro-note">{prefs.level==='challenge'?8:5} petits défis · sans chronomètre</span></aside>
        </div>
        <section className="activities" aria-labelledby="activities-title"><div className="section-heading"><div><span className="eyebrow">CHACUN SON PETIT PAS</span><h2 id="activities-title">Comment veux-tu jouer ?</h2></div><span className="selected-pill">Aujourd’hui, on explore <b>{topic.id}</b></span></div><div className="activity-grid">{modes.map((m,i)=>{const Icon=icons[m.icon];return <button className={`activity-card activity-${i}`} key={m.id} onClick={()=>setExercise(m.id)}><span className="activity-icon"><Icon size={27} strokeWidth={1.7}/></span><span className="activity-copy"><strong>{m.name}</strong><span>{m.description}</span></span><span className="activity-arrow"><ArrowRight size={20}/></span></button>;})}</div></section>
      </>:<section className="garden-panel"><div className="garden-heading"><span className="eyebrow">TES PETITES VICTOIRES</span><h2>{progress.flowers?'Regarde ce que tu as fait pousser !':'La première fleur t’attend.'}</h2><p>Termine une séance pour faire pousser une fleur.</p></div><div className="flower-bed">{progress.flowers?Array.from({length:Math.min(progress.flowers,24)},(_,i)=><div className="earned-flower" key={i}><span aria-hidden="true">{['🌻','🌷','🌼','🌸'][i%4]}</span><small>Fleur {i+1}</small></div>):<div className="empty-garden"><Sprout size={70} strokeWidth={1.3}/><span>Une graine, plein de possibilités.</span></div>}</div>{progress.flowers>24&&<p>Et encore {progress.flowers-24} fleurs dans ta collection !</p>}<div className="explored"><span>Lettres explorées</span>{progress.completed.length?progress.completed.map(id=><button onClick={()=>{setSelected(id);setView('map');}} key={id}>{id}<Check size={14}/></button>):<span>Ton aventure commence ici.</span>}</div><History history={progress.history} storageError={storageError}/><button className="primary" onClick={()=>setView('map')}>Explorer les sons<ArrowRight size={19}/></button></section>}
      {audioError&&<p className="notice" role="status">L’enregistrement n’a pas pu être lu. Vérifie le son ou la connexion, puis réessaie.</p>}
      {storageError&&<p className="notice" role="status">Le navigateur ne permet pas d’enregistrer tes fleurs. Elles restent visibles pendant cette visite.</p>}
      <footer><span><Heart size={16}/> Ici, on apprend à son rythme.</span><button onClick={()=>setModal('parents')}><BookOpen size={16}/> Le coin des parents</button><span className="footer-signature"><Leaf size={16}/> Cultivons le plaisir de lire.</span></footer>
    </main>
    {exercise&&<Exercise key={`${selected}-${exercise}-${prefs.level}`} topic={topic} mode={exercise} level={prefs.level} onClose={()=>setExercise(null)} onComplete={complete}/>}
    {modal==='settings'&&<Modal title="Le confort de lecture" onClose={close}><p className="modal-intro">Choisis ce qui te fait du bien pour lire.</p><label className="setting-row"><span><strong>De plus grandes lettres</strong><small>Pour lire plus confortablement.</small></span><input type="checkbox" checked={prefs.large} onChange={e=>setPrefs(p=>({...p,large:e.target.checked}))}/></label><label className="setting-row"><span><strong>Un texte plus aéré</strong><small>Plus d’espace entre les lettres et les mots.</small></span><input type="checkbox" checked={prefs.spaced} onChange={e=>setPrefs(p=>({...p,spaced:e.target.checked}))}/></label><fieldset className="level-settings"><legend>Qu’allons-nous lire ?</legend>{levels.map(l=><label key={l.id}><input type="radio" name="level" checked={prefs.level===l.id} onChange={()=>setPrefs(p=>({...p,level:l.id}))}/>{l.name}<span>{l.description}</span></label>)}</fieldset><div className="voice-setting"><Volume2 size={20}/><div><strong>Une voix douce, toujours la même</strong><p>Voix française de synthèse préenregistrée. Les syllabes ambiguës utilisent une prononciation corrigée.</p></div><button className="text-button" onClick={()=>say('papillon')}>Écouter</button></div><button className="primary wide" onClick={close}>C’est parti !<ArrowRight size={19}/></button></Modal>}
    {modal==='parents'&&<Modal title="Le coin des parents" onClose={close}><div className="parent-content"><p>Ce jardin propose un entraînement ludique à la lecture. La carte mentale relie les lettres aux syllabes et aux mots.</p><h3>Une petite séance, beaucoup de douceur</h3><ul><li>Choisissez une seule lettre ou un seul groupe de lettres.</li><li>Choisissez « Les mots » pour commencer. « Le grand défi » mélange les branches et propose six réponses proches. « Je repère » reste un échauffement pour les lettres.</li><li>Dans « Je lis », Elisabeth lit le texte puis choisit le son correspondant. Les réponses ne montrent pas le texte quand l’audio fonctionne.</li><li>Les mots et syllabes sont préenregistrés avec une voix française de synthèse. Les syllabes ambiguës sont produites avec des homophones : vo comme veau, vai comme vais. Vérifiez ensemble les sons lors de la première utilisation.</li><li>Dans « Les mots en images », le mot peut aussi être écouté directement. Cette écoute est une aide dans le bilan. Dans « La chenille des mots », il faut écouter puis choisir le bon mot : une réponse juste fait avancer la chenille ; une erreur la laisse sur place. Le bilan distingue les réponses trouvées du premier coup sans indice. Une fleur récompense chaque séance terminée, même avec plusieurs essais.</li></ul><h3>Quelques repères</h3><p>Le e a plusieurs prononciations. Le q est généralement étudié avec u. Les sons de ai peuvent varier selon les mots et les accents. Les mots peuvent contenir des lettres encore inconnues : accompagnez leur lecture.</p><p>Ce support ne remplace pas un accompagnement orthophonique et ne mesure pas le niveau de lecture.</p><p className="privacy-note">Les préférences, les fleurs et les 100 dernières séances restent dans ce navigateur (localStorage). La sauvegarde est propre à chaque adresse du site et à chaque appareil. Aucun compte enfant, aucun enregistrement de voix.</p><p>Dessins : <a href="https://openmoji.org/" target="_blank" rel="noreferrer">OpenMoji</a>, sous licence CC BY-SA 4.0. Repères : <a href="https://cdn.bdadyslexia.org.uk/uploads/documents/Advice/style-guide/BDA-Style-Guide-2023.pdf?v=1680084017" target="_blank" rel="noreferrer">British Dyslexia Association</a> · <a href="https://www.reseau-canope.fr/fileadmin/user_upload/Projets/conseil_scientifique_education_nationale/MANUELS_CSEN_VDEF.pdf" target="_blank" rel="noreferrer">CSEN / Réseau Canopé</a>.</p></div></Modal>}
  </div>;
}
