// Original, unmodified OpenMoji drawings, CC BY-SA 4.0. See public/illustrations/ATTRIBUTION.md.
const picture = (code, near) => ({code, near, src:`/illustrations/${code}.svg`});
export const pictures = {
  papillon:picture('1F98B',['pavillon','papille','papillon']),
  poule:picture('1F414',['boule','poulpe','poule']),
  pomme:picture('1F34E',['paume','pompe','pomme']),
  poire:picture('1F350',['foire','poêle','poire']),
  piano:picture('1F3B9',['pion','piano','panneau']),
  ballon:picture('1F388',['bâton','vallon','ballon']),
  banane:picture('1F34C',['cabane','banane','baleine']),
  bateau:picture('26F5',['bâton','gâteau','bateau']),
  bébé:picture('1F476',['bête','bébé','bêlé']),
  baleine:picture('1F40B',['balle','banane','baleine']),
  dé:picture('1F3B2',['dos','dé','doux']),
  dent:picture('1F9B7',['dinde','dent','don']),
  dauphin:picture('1F42C',['dindon','dauphin','demain']),
  dragon:picture('1F409',['drap','dragon','wagon']),
  drapeau:picture('1F6A9',['crapaud','drap','drapeau']),
  requin:picture('1F988',['refrain','requin','ravin']),
  coq:picture('1F413',['col','coq','cou']),
  raquette:picture('1F3F8',['raclette','raquette','roquette']),
  casque:picture('1FA96',['caisse','casque','cache']),
  quilles:picture('1F3B3',['quitte','quilles','billes']),
  fleur:picture('1F33C',['peur','fleur','fleuve']),
  fourmi:picture('1F41C',['four','fourmi','fourrure']),
  fusée:picture('1F680',['fumée','fusée','musée']),
  feuille:picture('1F343',['fille','feuille','foule']),
  fraise:picture('1F353',['phrase','fraise','fraise']),
  vélo:picture('1F6B2',['veau','vélo','vêtu']),
  vache:picture('1F404',['vase','vache','tache']),
  volcan:picture('1F30B',['volant','volcan','vocal']),
  voiture:picture('1F697',['voile','voiture','toiture']),
  violon:picture('1F3BB',['violet','violon','ballon']),
  renard:picture('1F98A',['regard','renard','retard']),
  cheval:picture('1F40E',['chemin','cheval','chenal']),
  cerise:picture('1F352',['chemise','cerise','crise']),
  repas:picture('1F37D',['repos','repas','retard']),
  étoile:picture('2B50',['étale','étoile','étude']),
  éléphant:picture('1F418',['élégant','éléphant','élément']),
  écureuil:picture('1F43F',['écueil','écureuil','écurie']),
  épée:picture('1F5E1',['épice','épée','épine']),
  balai:picture('1F9F9',['balcon','balai','ballon']),
  lait:picture('1F95B',['lit','lait','lot']),
  éclair:picture('26A1',['éclat','éclair','écrit']),
  maison:picture('1F3E0',['moisson','maison','saison']),
  oiseau:picture('1F426',['oiseau','ciseau','roseau']),
  poisson:picture('1F41F',['poison','poisson','poussin']),
  loup:picture('1F43A',['loupe','loup','lune']),
  souris:picture('1F42D',['sourire','souris','souci']),
  mouton:picture('1F411',['bouton','mouton','moulin']),
  hibou:picture('1F989',['bijou','hibou','caillou']),
};
// A broad label can legitimately name multiple pictures. Never offer those
// pictures as competing answers (an owl is a bird, a shark is a fish).
const ambiguousGroups=[['oiseau','hibou','coq','poule'],['poisson','requin'],['repas','pomme','poire','banane','fraise','cerise','lait','poisson']];
export const ambiguousPictures=(a,b)=>ambiguousGroups.some(group=>group.includes(a)&&group.includes(b));
export const pictureWords = {
  p:['papillon','poule','pomme','poire','piano'],
  b:['ballon','banane','bateau','bébé','baleine'],
  d:['dé','dent','dauphin','dragon','drapeau'],
  q:['requin','coq','raquette','casque','quilles'],
  f:['fleur','fourmi','fusée','feuille','fraise'],
  v:['vélo','vache','volcan','voiture','violon'],
  e:['renard','cheval','requin','cerise','repas'],
  é:['étoile','éléphant','écureuil','épée','vélo'],
  ai:['balai','lait','fraise','éclair','maison'],
  oi:['poire','étoile','voiture','oiseau','poisson'],
  ou:['loup','souris','poule','mouton','hibou'],
};
